kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels: 
      component: mysql
      project: expense
      tier: db
  templete:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0